# Generated by Django 4.2.11 on 2025-05-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomba', models.CharField(choices=[('A', 'Bomba A'), ('B', 'Bomba B'), ('C', 'Bomba C'), ('D', 'Bomba D')], max_length=1, unique=True)),
                ('combustivel', models.CharField(choices=[('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('gasolina_aditivada', 'Gasolina Aditivada')], max_length=20)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomba', models.CharField(choices=[('A', 'Bomba A'), ('B', 'Bomba B'), ('C', 'Bomba C'), ('D', 'Bomba D')], max_length=1)),
                ('combustivel', models.CharField(choices=[('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('gasolina_aditivada', 'Gasolina Aditivada')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
