# Generated by Django 4.2.11 on 2025-05-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id_bomba', models.CharField(choices=[('A', 'Bomba A'), ('B', 'Bomba B'), ('C', 'Bomba C'), ('D', 'Bomba D')], max_length=1, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecoCombustivel',
            fields=[
                ('id_combustivel', models.CharField(choices=[('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('gasolina_aditivada', 'Gasolina Aditivada'), ('diesel_s10', 'Diesel S10')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('preco_por_litro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Combustível (Preço)',
                'verbose_name_plural': 'Combustíveis (Preços)',
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('combustivel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gestaoPostoCombustivel.precocombustivel')),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tanque de Combustível',
                'verbose_name_plural': 'Tanques de Combustíveis',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoPostoCombustivel.bomba')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoPostoCombustivel.precocombustivel')),
            ],
        ),
        migrations.AddField(
            model_name='bomba',
            name='combustiveis_disponiveis',
            field=models.ManyToManyField(related_name='bombas_que_dispensam', to='gestaoPostoCombustivel.precocombustivel'),
        ),
    ]
