# Generated by Django 4.2.11 on 2025-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoPostoCombustivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoCombustivel',
            fields=[
                ('combustivel', models.CharField(choices=[('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('gasolina_aditivada', 'Gasolina Aditivada')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('preco_por_litro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preço de Combustível',
                'verbose_name_plural': 'Preços de Combustíveis',
            },
        ),
    ]
