# Generated by Django 4.2.11 on 2025-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoPostoCombustivel', '0002_precocombustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='capacidade_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
